version: '3.8'
services:
  main:
    container_name: Serve
    build:
      context: .
      dockerfile: Dockerfile
    command: [sh, -c, "php artisan storage:link && php artisan serve --host=0.0.0.0"]
    volumes:
      - .:/app
    ports:
      - 80:8000

  db:
    platform: linux/x86_64
    image: mysql:8.0
    container_name: Database
    environment:
      MYSQL_DATABASE: "otp_manager"
      MYSQL_USER: "user"
      MYSQL_ROOT: "root"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    volumes:
      - db:/var/lib/mysql
    ports:
      - 33061:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: PhpMyAdmin
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80

networks:
  laravel-exa:
    driver: bridge

volumes:
  db:
    driver: local
